services:
  emby-keeper:
    image: ghcr.io/coldboy404/emby-keeper:main
    container_name: emby-keeper
    restart: always

    environment:
      TZ: Asia/Shanghai

    volumes:
      - /vol1/1000/docker/embykeeper/app:/app

    # 如需连接宿主机代理可保留 host 网络；不需要时可删除。
    network_mode: host
